apiVersion: boundless.mirantis.com/v1alpha1
kind: Blueprint
metadata:
  name: k0s-cluster
spec:
  kubernetes:
    provider: k0s
    version: 1.28.5+k0s.0
    infra:
      hosts:
      - ssh:
          address: 10.0.0.1
          keyPath: ""
          port: 22
          user: root
        role: controller
      - ssh:
          address: 10.0.0.2
          keyPath: ""
          port: 22
          user: root
        role: worker
  components:
    addons:
    - name: example-server
      kind: chart
      enabled: true
      namespace: default
      chart:
        name: nginx
        repo: https://charts.bitnami.com/bitnami
        version: 15.1.1
        values: |
          "service":
            "type": "ClusterIP"
