apiVersion: bctl.mirantis.com/v1alpha1
kind: Blueprint
metadata:
  name: k0s-example
spec:
  kubernetes:
    provider: k0s
    version: 1.28.3+k0s.0
    infra:
      hosts:
      - localhost:
          enabled: true
        role: single
  components:
    addons:
      - name: ingress-nginx
        kind: chart
        enabled: true
        namespace: ingress-nginx
        chart:
          name: ingress-nginx
          repo: https://kubernetes.github.io/ingress-nginx
          version: latest
          values: |
            controller:
              service:
                nodePorts:
                  http: 30000
                  https: 30001
                type: NodePort
      - name: example-server
        kind: chart
        enabled: true
        namespace: default
        chart:
          name: nginx
          repo: https://charts.bitnami.com/bitnami
          version: 15.1.1
          values: |
            "service":
              "type": "ClusterIP"
