apiVersion: bctl.mirantis.com/v1alpha1
kind: Blueprint
metadata:
  name: lens-appiq-cluster
spec:
  kubernetes:
    provider: kind
  components:
    addons:
      - name: lens-appiq
        kind: chart
        enabled: true
        namespace: shipa-system
        chart:
          name: shipa
          repo: https://lensappiq-charts.storage.googleapis.com
          version: 0.1.0
          values: |
            auth:
              adminUser: "$LAIQ_USER" # Required, must be set
              adminPassword: "$LAIQ_PASSWORD" # Required, must be set
            shipaCluster:
              ingress:
                # SERVICE_TYPE can be ClusterIP or NodePort or LoadBalancer (default)
                serviceType: ClusterIP